"""Added columns for Responsible and Completion %

Revision ID: 48cb6a2edfb7
Revises: 
Create Date: 2024-11-30 16:09:05.783241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48cb6a2edfb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsible', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('completion_percent', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('completion_percent')
        batch_op.drop_column('responsible')

    # ### end Alembic commands ###
